프로그래머스 레벨2 - 과제진행하기 문제
yojessie/algorithm-note pull request #4
Opened 2023-08-31 10:18 UTC by yojessie

과제진행하기 문제를 풀었습니다.
생각의 과정을 노션에 기록해보았습니다.
https://buttercup-gargoyle-c70.notion.site/230826-99ee6514bba24fc99a9d304ee4b3b778?pvs=4

2023-08-31 13:24 UTC, f-lab-jake requested changes

2023-08-31 13:24 UTC, f-lab-jake commented on 02-programmers-lv2/230826-과제진행하기.js
> +  plans.sort((a, b) => {
`a[1]`, `b[1]`이 너무 많이 나옵니다.

2023-08-31 13:24 UTC, f-lab-jake commented on 02-programmers-lv2/230826-과제진행하기.js
> +    const callBefore = (leftMinutes) => {
왜 재귀로 했나요? 잘못한건 아닙니다.

2023-08-31 14:10 UTC, f-lab-jake requested changes

2023-08-31 14:10 UTC, f-lab-jake commented on 02-programmers-lv2/230826-과제진행하기.js
> +      time: {
`time`은 다루기 어렵습니다. 처음에 쓰기 쉬운 형태로 만들면 뒤에 코드가 간단해집니다.

2023-08-31 14:10 UTC, f-lab-jake commented on 02-programmers-lv2/230826-과제진행하기.js
> +    if (hourDiff === 1) {
서로 배타적인 조건문엔 else를 넣어주세요.

2023-08-31 14:10 UTC, f-lab-jake commented on 02-programmers-lv2/230826-과제진행하기.js
> +    if (i === plans.length - 1) {
요건 반복문 밖으로 빼주세요.

2023-09-01 02:15 UTC, yojessie commented on 02-programmers-lv2/230826-과제진행하기.js
> +  plans.sort((a, b) => {
풀어서 적었던 부분을 정리했습니다.
시각이 같을때 분을 비교할 수 있게 a - b 표현으로 수정했습니다.

2023-09-01 02:16 UTC, yojessie commented on 02-programmers-lv2/230826-과제진행하기.js
> +    if (hourDiff === 1) {
넵 결국 모든 경우의 수를 커버하는 조건문일때는 if, else if, else를 활용해 정리하겠습니다.

2023-09-01 02:17 UTC, yojessie commented on 02-programmers-lv2/230826-과제진행하기.js
> +    const callBefore = (leftMinutes) => {
남은 play 시간이 있을때
남은 시간을 가지고 stack에 쌓인 과목을 반복해서 처리하기위해 재귀함수를 사용했습니다.

2023-09-01 02:18 UTC, yojessie commented on 02-programmers-lv2/230826-과제진행하기.js
> +      time: {
time 오브젝트를 풀어서 저장하니 시,분 값에 바로 접근할 수 있었습니다.

2023-09-01 02:18 UTC, yojessie commented on 02-programmers-lv2/230826-과제진행하기.js
> +    if (i === plans.length - 1) {
마지막에 한번만 실행해도 되는 코드를 반복문 밖으로 빼고
스택에 요소가 있을때 뒤부터 pop시켜 답에 더할 수 있도록 수정했습니다.

2023-09-04 06:32 UTC, f-lab-jake requested changes

2023-09-04 06:32 UTC, f-lab-jake commented on 02-programmers-lv2/230826-과제진행하기.js
> +    const callBefore = (leftMinutes) => {
그렇다면 왜 for문을 사용하지 않았나요?

2023-09-04 06:32 UTC, f-lab-jake commented on 02-programmers-lv2/230829-귤고르기.js
> +  tangerine.map((v) => (count[v] += 1));
반환값을 사용하지 않을땐 `map`을 쓰지 말아주세요. 왜 그래야할까요?

2023-09-04 06:32 UTC, f-lab-jake commented on 02-programmers-lv2/230830-괄호회전하기.js
> +    const now = [...s.slice(i, s.length), ...s.slice(0, i)];
`rotated` 정도가 좋겠죠. 
가끔 정말 아무의미없는 변수이름을 지어야할때가 있는데, 그럴땐 그냥 `x` `y`나 배열이면 `xs` 정도를 추천합니다.
`now` 같은 애매한게 사람을 헷갈리게 합니다.

2023-09-04 06:32 UTC, f-lab-jake commented on 02-programmers-lv2/230830-괄호회전하기.js
> +    for (const j of now) {
틀린 문자열에대해 더빨리 실패할수있습니다

2023-09-04 06:32 UTC, f-lab-jake commented on 02-programmers-lv2/230831-n^2배열자르기.js
> +  for (let i = n - 2; i >= 0; i--) {
for를 반대방향말고 정방향으로 바꿀수있을까요?

2023-09-05 06:58 UTC, yojessie commented on 02-programmers-lv2/230826-과제진행하기.js
> +    const callBefore = (leftMinutes) => {
매 처리마다 달라지는 남은시간을 인자로 넣어주면서 활용하고싶었고,
스택에 쌓인 과목을 처리하는 일련의 과정을 한 함수에 묶어서 필요한 경우에 호출하고자 했습니다.

2023-09-05 07:05 UTC, yojessie commented on 02-programmers-lv2/230829-귤고르기.js
> +  tangerine.map((v) => (count[v] += 1));
생각해보니 map 함수는 콜백함수를 실행한 결과를 모아 새로운 배열로 반환하는데
위 코드에서는 그럴 필요가 없기 때문인것 같습니다.
이런경우에는 forEach를 사용하는게 더 나을까요?

2023-09-05 07:07 UTC, yojessie commented on 02-programmers-lv2/230830-괄호회전하기.js
> +    const now = [...s.slice(i, s.length), ...s.slice(0, i)];
아 넵 알겠습니다!

2023-09-05 07:49 UTC, yojessie commented on 02-programmers-lv2/230831-n^2배열자르기.js
> +  for (let i = n - 2; i >= 0; i--) {
넵 바꿀 수 있습니다.
처음에 배열에 값 할당하는 부분이 잘 안되서 생각하다가 저렇게 정리가 되었었네요.
정방향으로 반복문을 푸는것이 가독성이 더 좋고 자연스러운 것 같습니다.

2023-09-05 07:51 UTC, yojessie commented on 02-programmers-lv2/230830-괄호회전하기.js
> +    for (const j of now) {
rotate된 문자열을 구했을때
문자열의 시작이 닫는 괄호라면 무조건 틀리므로 해당 조건을 체크해 continue 하도록 수정했습니다.

2023-09-06 02:27 UTC, yojessie commented on 02-programmers-lv2/230826-과제진행하기.js
> +    return a[0] - b[0];
비교대상을 좀 더 간결하게 표현하기 위해
sort 메서드에 인자를 넘겨줄때 배열의 두번째 요소를 변수에 할당하여 수정

2023-09-06 02:28 UTC, yojessie commented on 02-programmers-lv2/230826-과제진행하기.js
> +      time: v[1][0] * 60 + v[1][1],
이 문제에서 필요한 것은 분단위 시간 비교이므로
hour값도 분단위로 수정하여 time 변수로 수정

2023-09-06 02:28 UTC, yojessie commented on 02-programmers-lv2/230826-과제진행하기.js
> +    now.play -= next.time - now.time;
hour값을 모두 분단위로 수정하였으므로 시 단위 비교가 필요 없어짐

2023-09-06 02:30 UTC, yojessie commented on 02-programmers-lv2/230826-과제진행하기.js
> +      }
이전에 사용했던 재귀함수는 리턴값이 없이 내부 함수에서 전역변수의 값을 수정하는 코드였으므로 좋지 않은 코드였음
따라서 stack에 쌓인 항목만 처리할 수 있도록 for반복문으로 수정

2023-09-06 02:35 UTC, yojessie commented on 02-programmers-lv2/230829-귤고르기.js
> +  for (const i of tangerine) count[i] += 1;
map메서드는 콜백함수를 실행해 새로운 배열을 만들어내므로 이 문제에 적당하지 않음
forEach메서드는 return이 continue를 의미하게되고, 중간에 종료하자면 throw로 에러를 내는등 돌아가야함
이 문제에서는 간단하게 for반복으로 귤의 크기들을 count해주는 의미로 사용하는게 깔끔하겠다.

2023-09-10 14:31 UTC, f-lab-jake requested changes

2023-09-10 14:31 UTC, f-lab-jake commented on 02-programmers-lv2/230907-캐시.js
> +    cityStack.push(city);
`cityStack.includes(city)` 가 두번 쓰였습니다. 이게 왜 안좋을까요? 성능말구요!

2023-09-10 14:31 UTC, f-lab-jake commented on 02-programmers-lv2/230907-행렬의곱셈.js
> +    return arr2[0].map((_, i) => {
arrow function을 쓸거면 return까지 빼줍시다. 그리고 lodash를 써서 리팩토링해보세요.

2023-09-10 14:31 UTC, f-lab-jake commented on 02-programmers-lv2/230908-할인행사.js
> +    }
이부분을 함수로 빼봅시다.

2023-09-10 14:31 UTC, f-lab-jake commented on 02-programmers-lv2/230910-의상.js
> +    else clothMap.set(type, [name]);
같은 로직이 다른 모습으로 존재합니다.
빈 배열로 초기화하는 부분을 분리해봅시다.

2023-09-11 15:59 UTC, yojessie commented on 02-programmers-lv2/230907-캐시.js
> +    cityStack.push(city);
`cityStack.includes(city)` 조건문 안에서 answer를 처리하려고 하다가
결국 includes를 두 번 쓴 이유는 시간초과 문제가 없는 상황에서라면
answer를 처리하는 영역과 cityStack을 처리하는 영역을 나눠서 정리하는게 더 이해하기 좋지 않을까 하는 생각이었습니다.

안좋은 코드라면 오히려 includes 조건문이 반복되기 때문일까요?

2023-09-12 02:00 UTC, f-lab-jake commented on 02-programmers-lv2/230907-캐시.js
> +    cityStack.push(city);
저번에 말씀드린 변수명 짓기를 다시 떠올려보세요
```ts
const ? = cityStack.includes(city)
```
좋은 의미를 나타낼 변수명이 있을까요?

2023-09-12 07:12 UTC, yojessie commented on 02-programmers-lv2/230908-할인행사.js
> +    }
`want`와 `tenDays` 배열의 아이템 수가 같은지 체크해서 bloolean을 반환하는 함수를 만들었습니다

2023-09-12 13:58 UTC, yojessie commented on 02-programmers-lv2/230907-캐시.js
> +  const cache = [];
기존에 변수명을 stack으로 했던 것은 잘못됨
스택 구조로 동작하는 코드가 아니므로 의미에 맞게 cache로 변수명을 수정

2023-09-12 14:01 UTC, yojessie commented on 02-programmers-lv2/230907-캐시.js
> +    const isCacheHit = cacheHitIndex !== -1;
도시 이름이 있는지 확인하는 코드를 한번만 실행할 수 있도록 변수에 할당하고
캐시 배열에 도시이름이 있는지 확인하는 변수를 명시적으로 작성

2023-09-12 14:02 UTC, yojessie commented on 02-programmers-lv2/230907-캐시.js
> +      cache.push(city);
`cacheSize`가 0이 아닌경우에만 push

2023-09-12 14:03 UTC, yojessie commented on 02-programmers-lv2/230907-행렬의곱셈.js
> +function solution(matrix1, matrix2) {
의미없는 arr라는 변수명은 사용하지 말 것

배열을 사용할때는 내부의 값을 사용하겠다는 의미이므로
무슨의미의 배열인지 변수명에 표시해줘야 함

2023-09-12 14:05 UTC, yojessie commented on 02-programmers-lv2/230910-의상.js
> +    }
저장된 `type` 속성이 없는 경우, 값을 초기화 하는 코드를 별도로 분리

2023-09-12 14:06 UTC, yojessie commented on 02-programmers-lv2/230907-캐시.js
> +    const isCacheHit = cacheHitIndex !== -1;
`indexOf` 메소드 사용 시 찾는 값이 없다면 -1이 반환된다

2023-09-12 14:35 UTC, yojessie commented on 02-programmers-lv2/230907-행렬의곱셈.js
> +    const column = _.range(matrix2[0].length);
lodash의 range함수 활용

2023-09-12 15:07 UTC, f-lab-jake approved these changes

2023-09-12 15:49 UTC, merged